config/routes.rb
SampleApp::Application.routes.draw do

  resources :users do
    member do
      get :following, :admirers, :messages_to, :messages_from
    end
  end

  resources :sessions, :only=> [:new, :create, :destroy]
  resources :microposts, :only=> [:destroy]
  resources :relationships, :only=> [:create, :destroy]

  match '/signup',  :to=> 'users#new'
  match '/profile',  :to=> 'users#show'
  match '/signin',  :to=> 'sessions#new'
  match '/signout', :to=> 'sessions#destroy', :via=> :delete

  match '/contact', :to=> 'static_pages#contact'
  match '/about', :to=> 'static_pages#about'
  match '/help',  :to=> 'static_pages#help'

   match '/course',  :to=> 'static_pages#courses'
    match '/bugs',  :to=> 'static_pages#bug'
    match '/teach',  :to=> 'static_pages#teach'
    match '/html5',  :to=> 'static_pages#les1'
     match '/android',  :to=> 'static_pages#les2'
 match '/home',  :to=> 'static_pages#home'
  root      :to=> 'users#index'

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li>* <%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts span6">
    <%= render :partial=> 'shared/feed_item', :collection=> @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
    <span class="content">
 <%= link_to image_tag avatarzz_url feed_item.user %>
 

    <% if feed_item.is_reply_to? %>
      <%= link_to "@#{feed_item.in_reply_to.username}", feed_item.in_reply_to %>
      <%= wrap(feed_item.content.gsub(/\A^@\w+/, "")) %>
    <% else %>
      <%= wrap(feed_item.content) %>
    <% end %>
  </span>
  <span class="timestamp">

    <%= link_to feed_item.user.username, feed_item.user %> posted
    <%= time_ago_in_words(feed_item.created_at) %> ago
    <% if feed_item.is_reply_to? %>
      in reply to <%= feed_item.in_reply_to.username %>.
    <% end %>
  </span>

  <% if current_user?(feed_item.user) %>

    <%= link_to "delete", feed_item, :method=> :delete,
      :data=> { :confirm=> "You sure?" },
      :title=> feed_item.content %>
  <% end %>
</li>

app/views/shared/_home.html.erb
<% provide(:title, 'Home') %>
</div>
<center><%=image_tag("http://i48.tinypic.com/313k8xe.png")%>


</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>

<%=image_tag("http://i49.tinypic.com/303li8k.png")%>

<%=image_tag("http://i49.tinypic.com/15nlr1l.png")%>
</br>
</br>
</br>
</br>
</br>
</br>
<%=image_tag("http://i50.tinypic.com/mwbr7l.png")%>

<%=image_tag("http://i47.tinypic.com/9lap1d.png")%>

</body>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <div class="field">
        <%= f.text_area :content, placeholder: "Compose new micropost..." %>
    </div>
    <span class="countdown"></span></br>
    <%= f.submit "Post", class: "btn btn-large btn-primary" %>
    

<% end %>

app/views/shared/_microposts.html.erb
<table class="front" summary="For signed-in users">
  <tr>
    <td class="main">
      <h1 class="micropost">What's up?</h1>
      <%= render 'shared/micropost_form' %>
      <%= render 'shared/feed' %>
    </td>
    <td class="sidebar round">
      <%= render 'shared/user_info' %>
      <%= render 'shared/stats' %>
    </td>
  </tr>
</table>

app/views/shared/_parser_form.html.erb
<%= form_tag '/parser' do %>
  <!--%= render 'shared/error_messages', :object => f.object %-->
  <div class="field">
    <%= text_area_tag 'command', params[:command],:maxlength=> 140, :placeholder=> "Holla, holla, playa! Wazzup?" %>
  </div>
  <span class="countdown"></span>
  <%= submit_tag "Post", :class=> "btn btn-large btn-primary", :name=> nil %>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<center>
<div class="stats">
  <div class="stats">
  <a href="<%=user_path(@user)%>">
    <strong id="microposts" class="stat">
      <%= @user.microposts.count %>
    </strong>
    posts
  </a> 

  <a href="<%= admirers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    admirers
  </a>
</div>
</center>

app/views/shared/_user_info.html.erb
<a href="<%= user_path(current_user) %>">
<center>  <%= image_tag avatar_url current_user, :size=> 50	 %> </center>
</a>
</br>
<h1><center><%= current_user.username %></center></h1>

app/views/shared/_user_navb.html.erb
<a href="<%= user_path(current_user) %>">
	  <g><%= image_tag avatan_url current_user, :size=> 20 %>   <%= current_user.username%></g>
	</a>